import * as fs from 'node:fs/promises';

// Map from uglyNameAsUsedOnCreaturePage => prettyName.
const normalizedPluralizedToPrettyNames = new Map([
	// Infuriatingly, we cannot just reuse the name mappings from the
	// kill stats at [1] since the creatures page has its own unique
	// casings.
	// [1]: https://github.com/tibiamaps/tibia-kill-stats/blob/HEAD/normalize-names.mjs
	['Acid Blobs', 'acid blob'],
	['Acolytes Of The Cult', 'acolyte of the cult'],
	['Adepts Of The Cult', 'adept of the cult'],
	['Adult Goannas', 'adult goanna'],
	['Afflicted Striders', 'afflicted strider'],
	['Amazons', 'amazon'],
	['Ancient Scarabs', 'ancient scarab'],
	['Angry Sugar Fairies', 'angry sugar fairy'],
	['Animated Feathers', 'animated feather'],
	['Arachnophobicas', 'arachnophobica'],
	['Arctic Fauns', 'arctic faun'],
	['Armadiles', 'armadile'],
	['Assassins', 'assassin'],
	['Azure Frogs', 'azure frog'],
	['Badgers', 'badger'],
	['Bandits', 'bandit'],
	['Banshees', 'banshee'],
	['Barbarian Bloodwalkers', 'barbarian bloodwalker'],
	['Barbarian Brutetamers', 'barbarian brutetamer'],
	['Barbarian Headsplitters', 'barbarian headsplitter'],
	['Barbarian Skullhunters', 'barbarian skullhunter'],
	['Barkless Devotees', 'barkless devotee'],
	['Barkless Fanatics', 'barkless fanatic'],
	['Bashmus', 'bashmu'],
	['Bats', 'bat'],
	['Bears', 'bear'],
	['Behemoths', 'behemoth'],
	['Betrayed Wraiths', 'betrayed wraith'],
	['Biting Books', 'biting book'],
	['Black Knights', 'black knight'],
	['Black Sphinx Acolytes', 'black sphinx acolyte'],
	['Blemished Spawns', 'blemished spawn'],
	['Blightwalkers', 'blightwalker'],
	['Bloated Man-maggots', 'bloated man-maggot'],
	['Blood Beasts', 'blood beast'],
	['Blood Crabs', 'blood crab'],
	['Blood Hands', 'blood hand'],
	['Blood Priests', 'blood priest'],
	['Blue Djinns', 'blue djinn'],
	['Boar Men', 'boar man'],
	['Boars', 'boar'],
	['Bog Frogs', 'bog frog'],
	['Bog Raiders', 'bog raider'],
	['Bonebeasts', 'bonebeast'],
	['Bonelords', 'bonelord'],
	['Bony Sea Devils', 'bony sea devil'],
	['Boogies', 'boogy'],
	['Brachiodemons', 'brachiodemon'],
	['Brain Squids', 'brain squid'],
	['Braindeaths', 'braindeath'],
	['Branchy Crawlers', 'branchy crawler'],
	['Breach Broods', 'breach brood'],
	['Brimstone Bugs', 'brimstone bug'],
	['Brinebrute Inferniarches', 'brinebrute inferniarch'],
	['Broken Shapers', 'broken shaper'],
	['Broodrider Inferniarches', 'broodrider inferniarch'],
	['Bugs', 'bug'],
	['Bulltaur Alchemists', 'bulltaur alchemist'],
	['Bulltaur Brutes', 'bulltaur brute'],
	['Bulltaur Forgepriests', 'bulltaur forgepriest'],
	['Burning Books', 'burning book'],
	['Burning Gladiators', 'burning gladiator'],
	['Burster Spectres', 'burster spectre'],
	['Butterflies', 'butterfly'],
	['Calamaries', 'calamary'],
	['Candy Floss Elementals', 'candy floss elemental'],
	['Candy Horrors', 'candy horror'],
	['Capricious Phantoms', 'capricious phantom'],
	['Carniphilas', 'carniphila'],
	['Carnisylvan Saplings', 'carnisylvan sapling'],
	['Carnivostriches', 'carnivostrich'],
	['Carrion Worms', 'carrion worm'],
	['Cats', 'cat'],
	['Cave Chimeras', 'cave chimera'],
	['Cave Devourers', 'cave devourer'],
	['Cave Rats', 'cave rat'],
	['Centipedes', 'centipede'],
	['Chakoya Toolshapers', 'chakoya toolshaper'],
	['Chakoya Tribewardens', 'chakoya tribewarden'],
	['Chakoya Windcallers', 'chakoya windcaller'],
	['Chasm Spawns', 'chasm spawn'],
	['Chickens', 'chicken'],
	['Chocolate Blobs', 'chocolate blob'],
	['Choking Fears', 'choking fear'],
	['Clay Guardians', 'clay guardian'],
	['Cliff Striders', 'cliff strider'],
	['Cloaks Of Terror', 'cloak of terror'],
	['Clomps', 'clomp'],
	['Cobra Assassins', 'cobra assassin'],
	['Cobra Scouts', 'cobra scout'],
	['Cobra Viziers', 'cobra vizier'],
	['Cobras', 'cobra'],
	['Converters', 'converter'],
	['Corym Charlatans', 'corym charlatan'],
	['Corym Skirmishers', 'corym skirmisher'],
	['Corym Vanguards', 'corym vanguard'],
	['Courage Leeches', 'courage leech'],
	['Crabs', 'crab'],
	['Crape Men', 'crape man'],
	['Crawlers', 'crawler'],
	['Crazed Beggars', 'crazed beggar'],
	['Crazed Summer Rearguards', 'crazed summer rearguard'],
	['Crazed Summer Vanguards', 'crazed summer vanguard'],
	['Crazed Winter Rearguards', 'crazed winter rearguard'],
	['Crazed Winter Vanguards', 'crazed winter vanguard'],
	['Cream Blobs', 'cream blob'],
	['Crocodiles', 'crocodile'],
	['Crustaceae Giganticae', 'crustacea gigantica'],
	['Crypt Defilers', 'crypt defiler'],
	['Crypt Shamblers', 'crypt shambler'],
	['Crypt Wardens', 'crypt warden'],
	['Crypt Warriors', 'crypt warrior'],
	['Crystal Spiders', 'crystal spider'],
	['Crystalcrushers', 'crystalcrusher'],
	['Cult Believers', 'cult believer'],
	['Cult Enforcers', 'cult enforcer'],
	['Cult Scholars', 'cult scholar'],
	['Cunning Werepanthers', 'cunning werepanther'],
	['Cursed Apes', 'cursed ape'],
	['Cursed Books', 'cursed book'],
	['Cursed Prospectors', 'cursed prospector'],
	['Cyclopes Drone', 'cyclops drone'],
	['Cyclopes Smith', 'cyclops smith'],
	['Cyclopes', 'cyclops'],
	['Dark Apprentices', 'dark apprentice'],
	['Dark Carnisylvans', 'dark carnisylvan'],
	['Dark Fauns', 'dark faun'],
	['Dark Magicians', 'dark magician'],
	['Dark Monks', 'dark monk'],
	['Dark Torturers', 'dark torturer'],
	['Darklight Constructs', 'darklight construct'],
	['Darklight Emitters', 'darklight emitter'],
	['Darklight Matters', 'darklight matter'],
	['Darklight Sources', 'darklight source'],
	['Darklight Strikers', 'darklight striker'],
	['Dawnfire Asuras', 'dawnfire asura'],
	['Death Blobs', 'death blob'],
	['Deathling Scouts', 'deathling scout'],
	['Deathling Spellsingers', 'deathling spellsinger'],
	['Deepling Guards', 'deepling guard'],
	['Deepling Scouts', 'deepling scout'],
	['Deepling Spellsingers', 'deepling spellsinger'],
	['Deepling Warriors', 'deepling warrior'],
	['Deepling Workers', 'deepling worker'],
	['Deepworms', 'deepworm'],
	['Deer', 'deer'],
	['Defilers', 'defiler'],
	['Demon Outcasts', 'demon outcast'],
	['Demon Skeletons', 'demon skeleton'],
	['Demons', 'demon'],
	['Destroyers', 'destroyer'],
	['Devourers', 'devourer'],
	['Diabolic Imps', 'diabolic imp'],
	['Diamond Servants', 'diamond servant'],
	['Diremaws', 'diremaw'],
	['Distorted Phantoms', 'distorted phantom'],
	['Dogs', 'dog'],
	['Dragolisks', 'dragolisk'],
	['Dragon Hatchlings', 'dragon hatchling'],
	['Dragon Lord Hatchlings', 'dragon lord hatchling'],
	['Dragon Lords', 'dragon lord'],
	['Dragonlings', 'dragonling'],
	['Dragons', 'dragon'],
	['Draken Abominations', 'draken abomination'],
	['Draken Elites', 'draken elite'],
	['Draken Spellweavers', 'draken spellweaver'],
	['Draken Warmasters', 'draken warmaster'],
	['Draptors', 'draptor'],
	['Dread Intruders', 'dread intruder'],
	['Drillworms', 'drillworm'],
	['Dromedaries', 'dromedary'],
	['Druid\'s Apparitions', 'druid’s apparition'],
	['Dwarf Geomancers', 'dwarf geomancer'],
	['Dwarf Guards', 'dwarf guard'],
	['Dwarf Miners', 'dwarf miner'],
	['Dwarf Soldiers', 'dwarf soldier'],
	['Dwarfs', 'dwarf'],
	['Dworc Fleshhunters', 'dworc fleshhunter'],
	['Dworc Venomsnipers', 'dworc venomsniper'],
	['Dworc Voodoomasters', 'dworc voodoomaster'],
	['Earth Elementals', 'earth elemental'],
	['Efreet', 'efreet'],
	['Elder Bonelords', 'elder bonelord'],
	['Elder Wyrms', 'elder wyrm'],
	['Elephants', 'elephant'],
	['Elf Arcanists', 'elf arcanist'],
	['Elf Scouts', 'elf scout'],
	['Elves', 'elf'],
	['Emerald Damselflies', 'emerald damselfly'],
	['Emerald Tortoises', 'emerald tortoise'],
	['Energetic Books', 'energetic book'],
	['Energuardians Of Tales', 'energuardian of tales'],
	['Energy Elementals', 'energy elemental'],
	['Enfeebled Silencers', 'enfeebled silencer'],
	['Enlighteneds Of The Cult', 'enlightened of the cult'],
	['Enraged Crystal Golems', 'enraged crystal golem'],
	['Enslaved Dwarfs', 'enslaved dwarf'],
	['Evil Prospectors', 'evil prospector'],
	['Execowtioners', 'execowtioner'],
	['Exotic Bats', 'exotic bat'],
	['Exotic Cave Spiders', 'exotic cave spider'],
	['Eyeless Devourers', 'eyeless devourer'],
	['Falcon Knights', 'falcon knight'],
	['Falcon Paladins', 'falcon paladin'],
	['Fauns', 'faun'],
	['Feral Sphinxes', 'feral sphinx'],
	['Feral Werecrocodiles', 'feral werecrocodile'],
	['Feversleeps', 'feversleep'],
	['Filth Toads', 'filth toad'],
	['Fire Devils', 'fire devil'],
	['Fire Elementals', 'fire elemental'],
	['Firestarters', 'firestarter'],
	['Fish', 'fish'],
	['Flamingos', 'flamingo'],
	['Flimsy Lost Souls', 'flimsy lost soul'],
	['Floating Savants', 'floating savant'],
	['Flying Books', 'flying book'],
	['Foam Stalkers', 'foam stalker'],
	['Forest Furies', 'forest fury'],
	['Foxes', 'fox'],
	['Frazzlemaws', 'frazzlemaw'],
	['Freakish Lost Souls', 'freakish lost soul'],
	['Frost Dragon Hatchlings', 'frost dragon hatchling'],
	['Frost Dragons', 'frost dragon'],
	['Frost Flower Asuras', 'frost flower asura'],
	['Frost Giantesses', 'frost giantess'],
	['Frost Giants', 'frost giant'],
	['Frost Trolls', 'frost troll'],
	['Fruit Drops', 'fruit drop'],
	['Furies', 'fury'],
	['Gang Members', 'gang member'],
	['Gargoyles', 'gargoyle'],
	['Gazer Spectres', 'gazer spectre'],
	['Gazers', 'gazer'],
	['Ghastly Dragons', 'ghastly dragon'],
	['Ghosts', 'ghost'],
	['Ghouls', 'ghoul'],
	['Giant Spiders', 'giant spider'],
	['Gingerbread Mans', 'gingerbread man'],
	['Girtablilu Warriors', 'girtablilu warrior'],
	['Gladiators', 'gladiator'],
	['Gloom Wolves', 'gloom wolf'],
	['Glooth Anemones', 'glooth anemone'],
	['Glooth Bandits', 'glooth bandit'],
	['Glooth Blobs', 'glooth blob'],
	['Glooth Brigands', 'glooth brigand'],
	['Glooth Golems', 'glooth golem'],
	['Gnarlhounds', 'gnarlhound'],
	['Goblin Assassins', 'goblin assassin'],
	['Goblin Scavengers', 'goblin scavenger'],
	['Goblins', 'goblin'],
	['Goggle Cakes', 'goggle cake'],
	['Golden Servants', 'golden servant'],
	['Gore Horns', 'gore horn'],
	['Gorerillas', 'gorerilla'],
	['Gorger Inferniarches', 'gorger inferniarch'],
	['Gozzlers', 'gozzler'],
	['Grave Robbers', 'grave robber'],
	['Gravediggers', 'gravedigger'],
	['Green Djinns', 'green djinn'],
	['Grim Reapers', 'grim reaper'],
	['Grimeleeches', 'grimeleech'],
	['Gryphons', 'gryphon'],
	['Guardians Of Tales', 'guardian of tales'],
	['Guzzlemaws', 'guzzlemaw'],
	['Hands Of Cursed Fate', 'hand of cursed fate'],
	['Harpies', 'harpy'],
	['Haunted Treelings', 'haunted treeling'],
	['Headpeckers', 'headpecker'],
	['Hellfire Fighters', 'hellfire fighter'],
	['Hellflayers', 'hellflayer'],
	['Hellhounds', 'hellhound'],
	['Hellhunter Inferniarches', 'hellhunter inferniarch'],
	['Hellspawns', 'hellspawn'],
	['Heroes', 'hero'],
	['Hideous Fungi', 'hideous fungus'],
	['Honey Elementals', 'honey elemental'],
	['Hulking Carnisylvans', 'hulking carnisylvan'],
	['Hulking Prehemoths', 'hulking prehemoth'],
	['Humongous Fungi', 'humongous fungus'],
	['Hunters', 'hunter'],
	['Huskies', 'husky'],
	['Hyaenas', 'hyaena'],
	['Hydras', 'hydra'],
	['Ice Golems', 'ice golem'],
	['Ice Witches', 'ice witch'],
	['Icecold Books', 'icecold book'],
	['Iks Aucars', 'iks aucar'],
	['Iks Chukas', 'iks chuka'],
	['Iks Pututus', 'iks pututu'],
	['Iks Yapunacs', 'iks yapunac'],
	['Infernal Demons', 'infernal demon'],
	['Infernal Phantoms', 'infernal phantom'],
	['Infernalists', 'infernalist'],
	['Ink Blobs', 'ink blob'],
	['Insane Sirens', 'insane siren'],
	['Insect Swarms', 'insect swarm'],
	['Insectoid Scouts', 'insectoid scout'],
	['Insectoid Workers', 'insectoid worker'],
	['Instable Breach Broods', 'instable breach brood'],
	['Instable Sparkions', 'instable sparkion'],
	['Iron Servants', 'iron servant'],
	['Ironblights', 'ironblight'],
	['Island Trolls', 'island troll'],
	['Jellyfish', 'jellyfish'],
	['Juggernauts', 'juggernaut'],
	['Jungle Moas', 'jungle moa'],
	['Juvenile Bashmus', 'juvenile bashmu'],
	['Killer Caimans', 'killer caiman'],
	['Knight\'s Apparitions', 'knight’s apparition'],
	['Knowledge Elementals', 'knowledge elemental'],
	['Kollos', 'kollos'],
	['Kongras', 'kongra'],
	['Ladybugs', 'ladybug'],
	['Lamassus', 'lamassu'],
	['Lancer Beetles', 'lancer beetle'],
	['Larvas', 'larva'],
	['Lava Golems', 'lava golem'],
	['Lava Lurkers', 'lava lurker'],
	['Lavafungi', 'lavafungus'],
	['Lavaworms', 'lavaworm'],
	['Leaf Golems', 'leaf golem'],
	['Liches', 'lich'],
	['Liodiles', 'liodile'],
	['Lions', 'lion'],
	['Lizard Chosens', 'lizard chosen'],
	['Lizard Dragon Priests', 'lizard dragon priest'],
	['Lizard High Guards', 'lizard high guard'],
	['Lizard Legionnaires', 'lizard legionnaire'],
	['Lizard Sentinels', 'lizard sentinel'],
	['Lizard Snakecharmers', 'lizard snakecharmer'],
	['Lizard Templars', 'lizard templar'],
	['Lizard Zaoguns', 'lizard zaogun'],
	['Lost Bashers', 'lost basher'],
	['Lost Berserkers', 'lost berserker'],
	['Lost Hushers', 'lost husher'],
	['Lost Souls', 'lost soul'],
	['Lost Throwers', 'lost thrower'],
	['Lumbering Carnivors', 'lumbering carnivor'],
	['Mad Scientists', 'mad scientist'],
	['Magma Crawlers', 'magma crawler'],
	['Makaras', 'makara'],
	['Mammoths', 'mammoth'],
	['Manta Rays', 'manta ray'],
	['Manticores', 'manticore'],
	['Mantosauruses', 'mantosauruse'],
	['Many Faces', 'many faces'],
	['Marid', 'marid'],
	['Marsh Stalkers', 'marsh stalker'],
	['Massive Earth Elementals', 'massive earth elemental'],
	['Massive Energy Elementals', 'massive energy elemental'],
	['Massive Fire Elementals', 'massive fire elemental'],
	['Massive Water Elementals', 'massive water elemental'],
	['Mean Lost Souls', 'mean lost soul'],
	['Meandering Mushrooms', 'meandering mushroom'],
	['Medusae', 'medusa'],
	['Mega Dragons', 'mega dragon'],
	['Menacing Carnivors', 'menacing carnivor'],
	['Mercurial Menaces', 'mercurial menace'],
	['Mercury Blobs', 'mercury blob'],
	['Merlkins', 'merlkin'],
	['Metal Gargoyles', 'metal gargoyle'],
	['Midnight Asuras', 'midnight asura'],
	['Midnight Panthers', 'midnight panther'],
	['Minotaur Amazons', 'minotaur amazon'],
	['Minotaur Archers', 'minotaur archer'],
	['Minotaur Cult Followers', 'minotaur cult follower'],
	['Minotaur Cult Prophets', 'minotaur cult prophet'],
	['Minotaur Cult Zealots', 'minotaur cult zealot'],
	['Minotaur Guards', 'minotaur guard'],
	['Minotaur Hunters', 'minotaur hunter'],
	['Minotaur Mages', 'minotaur mage'],
	['Minotaurs', 'minotaur'],
	['Mirror Images', 'mirror image'],
	['Misguided Bullies', 'misguided bully'],
	['Misguided Thieves', 'misguided thief'],
	['Mitmah Scouts', 'mitmah scout'],
	['Mitmah Seers', 'mitmah seer'],
	['Monks Of The Order', 'monk of the order'],
	['Monks', 'monk'],
	['Mooh\'tah Warriors', 'mooh’tah warrior'],
	['Moohtants', 'moohtant'],
	['Mould Phantoms', 'mould phantom'],
	['Mummies', 'mummy'],
	['Mutated Bats', 'mutated bat'],
	['Mutated Humans', 'mutated human'],
	['Mutated Rats', 'mutated rat'],
	['Mutated Tigers', 'mutated tiger'],
	['Mycobiontic Beetles', 'mycobiontic beetle'],
	['Naga Archers', 'naga archer'],
	['Naga Warriors', 'naga warrior'],
	['Necromancers', 'necromancer'],
	['Nibblemaws', 'nibblemaw'],
	['Nightfiends', 'nightfiend'],
	['Nighthunters', 'nighthunter'],
	['Nightmare Scions', 'nightmare scion'],
	['Nightmares', 'nightmare'],
	['Nightstalkers', 'nightstalker'],
	['Noble Lions', 'noble lion'],
	['Nomads', 'nomad'],
	['Northern Pikes', 'northern pike'],
	['Novices Of The Cult', 'novice of the cult'],
	['Noxious Ripptors', 'noxious ripptor'],
	['Nymphs', 'nymph'],
	['Ogre Brutes', 'ogre brute'],
	['Ogre Rowdies', 'ogre rowdy'],
	['Ogre Ruffians', 'ogre ruffian'],
	['Ogre Sages', 'ogre sage'],
	['Ogre Savages', 'ogre savage'],
	['Ogre Shamans', 'ogre shaman'],
	['Omnivoras', 'omnivora'],
	['Oozing Carcasses', 'oozing carcass'],
	['Oozing Corpuses', 'oozing corpus'],
	['Orc Berserkers', 'orc berserker'],
	['Orc Cult Fanatics', 'orc cult fanatic'],
	['Orc Cult Inquisitors', 'orc cult inquisitor'],
	['Orc Cult Minions', 'orc cult minion'],
	['Orc Cult Priests', 'orc cult priest'],
	['Orc Cultists', 'orc cultist'],
	['Orc Leaders', 'orc leader'],
	['Orc Marauders', 'orc marauder'],
	['Orc Riders', 'orc rider'],
	['Orc Shamans', 'orc shaman'],
	['Orc Spearmen', 'orc spearman'],
	['Orc Warlords', 'orc warlord'],
	['Orc Warriors', 'orc warrior'],
	['Orclops Doomhaulers', 'orclops doomhauler'],
	['Orclops Ravagers', 'orclops ravager'],
	['Orcs', 'orc'],
	['Orewalkers', 'orewalker'],
	['Paladin\'s Apparitions', 'paladin’s apparition'],
	['Pandas', 'panda'],
	['Parders', 'parder'],
	['Parrots', 'parrot'],
	['Penguins', 'penguin'],
	['Phantasms', 'phantasm'],
	['Pigeons', 'pigeon'],
	['Pigs', 'pig'],
	['Pirat Bombardiers', 'pirat bombardier'],
	['Pirat Cutthroats', 'pirat cutthroat'],
	['Pirat Mates', 'pirat mate'],
	['Pirat Scoundrels', 'pirat scoundrel'],
	['Pirate Buccaneers', 'pirate buccaneer'],
	['Pirate Corsairs', 'pirate corsair'],
	['Pirate Cutthroats', 'pirate cutthroat'],
	['Pirate Ghosts', 'pirate ghost'],
	['Pirate Marauders', 'pirate marauder'],
	['Pirate Skeletons', 'pirate skeleton'],
	['Pixies', 'pixie'],
	['Plaguesmiths', 'plaguesmith'],
	['Poachers', 'poacher'],
	['Poison Spiders', 'poison spider'],
	['Poisonous Carnisylvans', 'poisonous carnisylvan'],
	['Polar Bears', 'polar bear'],
	['Pookas', 'pooka'],
	['Priestesses Of The Wild Sun', 'priestess of the wild sun'],
	['Priestesses', 'priestess'],
	['Putrid Mummies', 'putrid mummy'],
	['Quara Constrictor Scouts', 'quara constrictor scout'],
	['Quara Constrictors', 'quara constrictor'],
	['Quara Hydromancer Scouts', 'quara hydromancer scout'],
	['Quara Hydromancers', 'quara hydromancer'],
	['Quara Looters', 'quara looter'],
	['Quara Mantassin Scouts', 'quara mantassin scout'],
	['Quara Mantassins', 'quara mantassin'],
	['Quara Pincher Scouts', 'quara pincher scout'],
	['Quara Pinchers', 'quara pincher'],
	['Quara Plunderers', 'quara plunderer'],
	['Quara Predator Scouts', 'quara predator scout'],
	['Quara Predators', 'quara predator'],
	['Quara Raiders', 'quara raider'],
	['Rabbits', 'rabbit'],
	['Rage Squids', 'rage squid'],
	['Rats', 'rat'],
	['Reality Reavers', 'reality reaver'],
	['Redeemed Souls', 'redeemed soul'],
	['Renegade Knights', 'renegade knight'],
	['Retching Horrors', 'retching horror'],
	['Rhindeer', 'rhindeer'],
	['Ripper Spectres', 'ripper spectre'],
	['Roaring Lions', 'roaring lion'],
	['Rootthing Amber Shapers', 'rootthing amber shaper'],
	['Rootthing Bug Trackers', 'rootthing bug tracker'],
	['Rootthing Nutshells', 'rootthing nutshell'],
	['Rorcs', 'rorc'],
	['Rot Elementals', 'rot elemental'],
	['Rotten Golems', 'rotten golem'],
	['Rotten Man-maggots', 'rotten man-maggot'],
	['Rotworms', 'rotworm'],
	['Rustheap Golems', 'rustheap golem'],
	['Sabreteeth', 'sabretooth'],
	['Salamanders', 'salamander'],
	['Sandcrawlers', 'sandcrawler'],
	['Sandstone Scorpions', 'sandstone scorpion'],
	['Scarabs', 'scarab'],
	['Scorpions', 'scorpion'],
	['Sea Serpents', 'sea serpent'],
	['Seacrest Serpents', 'seacrest serpent'],
	['Seagulls', 'seagull'],
	['Serpent Spawns', 'serpent spawn'],
	['Shadow Pupils', 'shadow pupil'],
	['Shaper Matriarches', 'shaper matriarch'],
	['Sharks', 'shark'],
	['Sheep', 'sheep'],
	['Shock Heads', 'shock head'],
	['Shrieking Cry-stals', 'shrieking cry-stal'],
	['Sibangs', 'sibang'],
	['Sights Of Surrender', 'sight of surrender'],
	['Silencers', 'silencer'],
	['Silver Rabbits', 'silver rabbit'],
	['Sineater Inferniarches', 'sineater inferniarch'],
	['Skeleton Elite Warriors', 'skeleton elite warrior'],
	['Skeleton Warriors', 'skeleton warrior'],
	['Skeletons', 'skeleton'],
	['Skunks', 'skunk'],
	['Slimes', 'slime'],
	['Slugs', 'slug'],
	['Smugglers', 'smuggler'],
	['Snakes', 'snake'],
	['Sons Of Verminor', 'son of Verminor'],
	['Sopping Carcasses', 'sopping carcass'],
	['Sopping Corpuses', 'sopping corpus'],
	['Sorcerer\'s Apparitions', 'sorcerer’s apparition'],
	['Soul-broken Harbingers', 'soul-broken harbinger'],
	['Souleaters', 'souleater'],
	['Sparkions', 'sparkion'],
	['Spectres', 'spectre'],
	['Spellreaper Inferniarches', 'spellreaper inferniarch'],
	['Sphinxes', 'sphinx'],
	['Spiders', 'spider'],
	['Spidris', 'spidris'],
	['Spiky Carnivors', 'spiky carnivor'],
	['Spit Nettles', 'spit nettle'],
	['Spitters', 'spitter'],
	['Squid Wardens', 'squid warden'],
	['Squirrels', 'squirrel'],
	['Stabilizing Dread Intruders', 'stabilizing dread intruder'],
	['Stabilizing Reality Reavers', 'stabilizing reality reaver'],
	['Stalkers', 'stalker'],
	['Stalking Stalks', 'stalking stalk'],
	['Stampors', 'stampor'],
	['Stone Devourers', 'stone devourer'],
	['Stone Golems', 'stone golem'],
	['Stone Rhinos', 'stone rhino'],
	['Streaked Devourers', 'streaked devourer'],
	['Sugar Cube Workers', 'sugar cube worker'],
	['Sugar Cubes', 'sugar cube'],
	['Sulphiders', 'sulphider'],
	['Sulphur Spouters', 'sulphur spouter'],
	['Swamp Trolls', 'swamp troll'],
	['Swamplings', 'swampling'],
	['Swan Maidens', 'swan maiden'],
	['Swarmers', 'swarmer'],
	['Tainted Souls', 'tainted soul'],
	['Tarantulas', 'tarantula'],
	['Tarnished Spirits', 'tarnished spirit'],
	['Terramites', 'terramite'],
	['Terror Birds', 'terror bird'],
	['Terrorsleeps', 'terrorsleep'],
	['Thanatursuses', 'thanatursus'],
	['Thornback Tortoises', 'thornback tortoise'],
	['Tigers', 'tiger'],
	['Toads', 'toad'],
	['Tortoises', 'tortoise'],
	['Tremendous Tyrants', 'tremendous tyrant'],
	['Troll Champions', 'troll champion'],
	['Trolls', 'troll'],
	['True Dawnfire Asuras', 'true dawnfire asura'],
	['True Frost Flower Asuras', 'true frost flower asura'],
	['True Midnight Asuras', 'true midnight asura'],
	['Truffle Cooks', 'truffle cook'],
	['Truffles', 'truffle'],
	['Tunnel Tyrants', 'tunnel tyrant'],
	['Turbulent Elementals', 'turbulent elemental'],
	['Twisted Pookas', 'twisted pooka'],
	['Twisted Shapers', 'twisted shaper'],
	['Two-headed Turtles', 'two-headed turtle'],
	['Undead Cavebears', 'undead cavebear'],
	['Undead Dragons', 'undead dragon'],
	['Undead Elite Gladiators', 'undead elite gladiator'],
	['Undead Gladiators', 'undead gladiator'],
	['Undertakers', 'undertaker'],
	['Usurper Archers', 'usurper archer'],
	['Usurper Commanders', 'usurper commander'],
	['Usurper Knights', 'usurper knight'],
	['Usurper Warlocks', 'usurper warlock'],
	['Valkyries', 'valkyrie'],
	['Vampire Brides', 'vampire bride'],
	['Vampire Viscounts', 'vampire viscount'],
	['Vampires', 'vampire'],
	['Varnished Diremaws', 'varnished diremaw'],
	['Venerable Girtablilus', 'venerable girtablilu'],
	['Vexclaws', 'vexclaw'],
	['Vibrant Phantoms', 'vibrant phantom'],
	['Vicious Manbats', 'vicious manbat'],
	['Vicious Squires', 'vicious squire'],
	['Vile Grandmasters', 'vile grandmaster'],
	['Vulcongras', 'vulcongra'],
	['Wailing Widows', 'wailing widow'],
	['Walkers', 'walker'],
	['Walking Pillars', 'walking pillar'],
	['Wandering Pillars', 'wandering pillar'],
	['War Golems', 'war golem'],
	['War Wolves', 'war wolf'],
	['Wardragons', 'wardragon'],
	['Warlocks', 'warlock'],
	['Waspoids', 'waspoid'],
	['Wasps', 'wasp'],
	['Water Buffalos', 'water buffalo'],
	['Water Elementals', 'water elemental'],
	['Weakened Frazzlemaws', 'weakened frazzlemaw'],
	['Weepers', 'weeper'],
	['Werebadgers', 'werebadger'],
	['Werebears', 'werebear'],
	['Wereboars', 'wereboar'],
	['Werecrocodiles', 'werecrocodile'],
	['Werefoxes', 'werefox'],
	['Werehyaena Shamans', 'werehyaena shaman'],
	['Werehyaenas', 'werehyaena'],
	['Werelionesses', 'werelioness'],
	['Werelions', 'werelion'],
	['Werepanthers', 'werepanthers'],
	['Weretigers', 'weretiger'],
	['Werewolves', 'werewolf'],
	['White Deer', 'white deer'],
	['White Lions', 'white lion'],
	['White Shades', 'white shade'],
	['White Tigers', 'white tiger'],
	['White Weretigers', 'white weretiger'],
	['Wigglers', 'wiggler'],
	['Wild Warriors', 'wild warrior'],
	['Wilting Leaf Golems', 'wilting leaf golem'],
	['Winter Wolves', 'winter wolf'],
	['Wisps', 'wisp'],
	['Witches', 'witch'],
	['Wolves', 'wolf'],
	['Worker Golems', 'worker golem'],
	['Worm Priestesses', 'worm priestess'],
	['Wyrms', 'wyrm'],
	['Wyverns', 'wyvern'],
	['Yielothax', 'yielothax'],
	['Young Goannas', 'young goanna'],
	['Young Sea Serpents', 'young sea serpent'],
	['Zombies', 'zombie'],
]);

// Map from uglyNameAsUsedInBoostedWidget => prettyName.
const normalizedSingularToPrettyNames = new Map([
	// Infuriatingly, we cannot just reuse the name mappings from the
	// kill stats at [1] since the creatures page has its own unique
	// casings.
	// [1]: https://github.com/tibiamaps/tibia-kill-stats/blob/HEAD/normalize-names.mjs
	['Son Of Verminor', 'son of Verminor'],
]);

export const pluralizedToPretty = (uglyPluralName) => {
	const prettyName = normalizedPluralizedToPrettyNames.get(uglyPluralName);
	if (!prettyName) {
		console.log(`Unknown pretty name for uglyPluralName=${JSON.stringify(uglyPluralName)}`);
		return uglyPluralName;
	}
	return prettyName;
};

export const singularToPretty = (uglySingularName) => {
	const prettyName = normalizedSingularToPrettyNames.get(uglySingularName);
	if (!prettyName) {
		return uglySingularName.replaceAll('\'', '’').toLowerCase();
	}
	return prettyName;
};

const test = async () => {
	const readUglyNames = async () => {
		const filePath = './data/ugly-names.json';
		const json = await fs.readFile(filePath);
		const array = JSON.parse(json);
		const set = new Set(array);
		return set;
	};

	const UGLY_NAMES = await readUglyNames();

	for (const [uglyName, prettyName] of normalizedPluralizedToPrettyNames) {
		console.assert(UGLY_NAMES.has(uglyName), `Expected ${uglyName} to appear in list of boostable creatures.`);
		if (uglyName !== prettyName) {
			console.assert(!UGLY_NAMES.has(prettyName), `Expected ${prettyName} to NOT appear in list of ugly boostable creature names.`);
		}
	}

	for (const name of UGLY_NAMES) {
		console.assert(normalizedPluralizedToPrettyNames.has(name), `Missing normalization map entry: ${name}`);
	}
};

if (process.env.TEST) {
	await test();
}
