name: 'Update data'

on:
  schedule:
    # During CET, run daily at 09:00 UTC (10:00 CET),
    # then again one hour later (in case of weekly server maintenance),
    # and then once more another hour later (in case of long-lasting maintenance).
    # - cron: '00 09 * * *'
    # - cron: '00 10 * * *'
    # - cron: '00 11 * * *'
    # During CEST, run daily at 08:00 UTC (10:00 CEST).
    - cron: '00 08 * * *'
    - cron: '00 09 * * *'
    - cron: '00 10 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Update data
        run: |
          npm run build
          git config user.name 'Tibia boosted creature bot'
          git config user.email 'boosted-creature@tibiamaps.io'
          git add data
          node commit-message.mjs > commit_message
          git commit data --file=commit_message || true
          rm commit_message
          git push
